import React from 'react';

function ExploreMDD() {
    return(
        <div className="dataVizContainer">
            <div className="dataSources">
            <h4>&#47;&#47; Sources &#47;&#47;</h4>
            <p><a href="https://www.imh.com.sg/research/" target="_blank" rel="noopener noreferrer">The Institute of Mental Health (IMH)</a>, <a href="https://www.wikipedia.org/" target="_blank" rel="noopener noreferrer">Wikipedia</a>, <a href="https://www.nice.org.uk/guidance/cg78/chapter/Introduction" target="_blank" rel="noopener noreferrer">National Institute for Health and Care Excellence</a>, <a href="https://www.cal.org.sg/post/2018/12/13/rise-in-estimated-number-of-caregivers-in-singapore" target="_blank" rel="noopener noreferrer">Caregivers Alliance Limited</a>, <a href="https://www.caregiver.org/caregiver-depression-silent-health-crisis" target="_blank" rel="noopener noreferrer">Family Caregiver Alliance</a>, <a href="https://ourworldindata.org/grapher/number-suffering-from-depression-by-region" target="_blank" rel="noopener noreferrer">Our World in Data</a>, <a href="https://www.moh.gov.sg/docs/librariesprovider5/resources-statistics/educational-resources/anxiety_disorder.pdf" target="_blank" rel="noopener noreferrer">Ministry of Health</a>, <a href="https://www.thelancet.com/journals/lanpsy/article/PIIS2215-0366(19)30031-8/fulltext" target="_blank" rel="noopener noreferrer">The Lancet</a>, <a href="https://www.healthhub.sg/a-z/diseases-and-conditions/49/topics_bipolar_disorder" target="_blank" rel="noopener noreferrer">Ministry of Health Singapore – Health Hub Publication</a>, <a href="https://www.msdmanuals.com/en-sg/home/mental-health-disorders/dissociative-disorders/dissociative-identity-disorder" target="_blank" rel="noopener noreferrer">MDS Manual</a>, <a href="https://www.nami.org/About-Mental-Illness/Mental-Health-Conditions/Dissociative-Disorders" target="_blank" rel="noopener noreferrer">National Alliance on Mental Health</a>, Rief W, Buhlmann U, Wilhelm S, Borkenhagen ADA, Brähler E (2006). <a href="https://d1wqtxts1xzle7.cloudfront.net/44642525/rief2006.pdf?1460425769=&response-content-disposition=inline%3B+filename%3DThe_prevalence_of_body_dysmorphic_disord.pdf&Expires=1605406271&Signature=UIqh9Hl6UzUbpmrzxfP5zIHoogccnftSBP1u-013TntuFBJV0pwYy0kmJ7B-a5G8X83vEfsOXs81qFAVtHsxDmOEPQimYXKzOpA0OhfBlTtG8DdrC3bR8UzD-DhiyDvjljqEZHbwokcEaZtsKSXVrC-kJ6fu2DqWyTe1aOAslEKyektCtPWmM3qvxQ4fpIdfye~Umd-Dfynqp9U~F37CCoHBPpoUJZ1mzoFp5FB9wNI1l~c6Wn9zxWtBouQtlTWwcK3DlpBfTzHBclLjnASn5wLeD-WtK5xm2ywdMfTSEYc62thOgJCuMKuW1bOHGxC0Xf8NFkC9QNvrsKckudaIaQ__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA" target="_blank" rel="noopener noreferrer">The prevalence of body dysmorphic disorder: a population-based survey</a>. Psychological Medicine 36, 877–885., Boroughs MS, Krawczyk R, Thompson JK (2010). <a href="https://link.springer.com/article/10.1007%252Fs11199-010-9831-1" target="_blank" rel="noopener noreferrer">Body dysmorphic disorder among diverse racial/ethnic and sexual orientation groups: prevalence estimates and associated factors</a>. Sex Roles 63, 725–737.
            </p>
            </div>
        </div>
    );
}

export default ExploreMDD;