export const IssueInfoData = [
    {id:0, 
      slug:'depression', 
      h1:'Depression / MDD', 
      number: '16', 
      img: '1-in-16',
      help: 'counselling',
      body:'Persistently depressed mood or loss of interest in activities causing significant impairment in daily life. The most common mental disorder in Singapore.'},
    {id:1, 
      slug:'bipolar', 
      h1:'Bipolar', 
      number: '62', 
      img: '1-in-62',
      help: 'counselling',
      body:'Episodes of mood swings ranging from depressive lows to manic highs. This disorder is characterised by depressive episodes and mania.'},
    {id:2, 
      slug:'anxiety', 
      h1:'Anxiety / GAD', 
      number: '62',
      img: '1-in-62',
      help: 'counselling',
      body:"Feelings of worry, anxiety, or fear that are strong enough to interfere with one's daily activities. They are often accompanied by other symptoms."},
    {id:3, 
      slug:'ocd', 
      h1:'Obessive Compulsive Disorder', 
      number: '28', 
      img: '1-in-28',
      help: 'counselling',
      body:'The occurrence of obsessions, compulsive rituals or, both recurrent and persistent thoughts, impulses, or images that are experienced as intrusive and cause great anxiety.'},
    {id:4, 
      slug:'alcohol-abuse', 
      h1:'Alcohol Abuse', 
      number: '28', 
      img: '1-in-28',
      help: 'specialists',
      body:'Recurrent alcohol use resulting in failure to fulfill major role obligations, or recurrent use in situations in which it is physically hazardous.'},
    {id:5, 
      slug:'did', 
      h1:'Dissociative Identity Disorder', 
      number: '67',
      img: '1-in-67', 
      help: 'counselling',
      body:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'},
    {id:6, 
      slug:'general', 
      h1:'Multiple issues', 
      number: '100', 
      img: '1-in-100',
      help: 'counselling',
      body:'Comorbidity, presence of two or more of the above mental disorders in the same period. Symptoms often overlap and can be additive.'},
    {id:7, 
      slug:'general', 
      h1:'Mental health issues', 
      number: '7', 
      img: '1-in-7',
      help: 'counselling',
      body:'A wide range of conditions that affect mood, thinking, and behavior. 1 in 7 people in Singapore has experienced mental issues, with only two of them seeking help.'},
    {id:8, 
      slug:'bdd', 
      h1:'Body Dysmorphic Disorder', 
      number: '50', 
      img: '1-in-50',
      help: 'counselling',
      body:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'},
    {id:9, 
      slug:'bpd', 
      h1:'Borderline Personality Disorder', 
      number: '101', 
      img: '1-in-101',
      help: 'counselling',
      body:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'},
    {id:10, 
      slug:'ptsd', 
      h1:'Post Traumatic Stress Disorder', 
      number: '19', 
      img: '1-in-19',
      help: 'counselling',
      body:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'},
    {id:11, 
      slug:'psychosis', 
      h1:'Psychosis', 
      number: '50', 
      img: '1-in-50',
      help: 'counselling',
      body:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'},
    {id:12, 
      slug:'eating-disorder', 
      h1:'Eating Disorder', 
      number: '200', 
      img: '1-in-200',
      help: 'specialists',
      body:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'},
    {id:13, 
      slug:'schizophrenia', 
      h1:'Schizophrenia', 
      number: '335', 
      img: '1-in-335',
      help: 'counselling',
      body:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'}];