export const PostData = [
    {   id: 0,
        quote:"I’ve lost some friends to depression, because they either felt that no one could understand them, or the stigma of mental illness prevents them from reaching out. This is why encouraging open discussion and acceptance of mental illnesses is so important. We should let our friends and family know that it’s ok to not be ok.",
        issue:"MDD / Depression",
        issueslug: "depression all",
        name:"–Sun Koh, Filmmaker"
    },
    {   id: 17,
        quote:"Everything hurts, but I want to believe everything can heal as well.",
        issue:"BPD / Borderline Personality Disorder",
        issueslug: "bpd all"
    },
    {   id: 1,
        quote:"While walking the streets of NYC one day I came across a sign that said “depression is a flaw of chemistry, not character.” Those words itself were enough to pierce an arrow deep into my psyche. Remember, you’re not alone and can get through this. I’m talking from 18 years of personal experience.",
        issue:"MDD / Depression",
        issueslug: "depression all",
        name:"–Sid Reddy, Wildlife Photographer, India"
    },
    {   id: 2,
        quote:"Much Madness is Divinest Sense - To a discerning Eye - Much Sense - the starkest Madness - ’Tis the Majority - In this, as all, prevail - Assent - and you are sane - Demur - you’re straightway dangerous - And handled with a Chain -",
        issue:"Bipolar",
        issueslug: "bipolar all",
        name:"–Emily Dickinson, American Poet"
    },
    {   id: 18,
        quote:"My recovery from manic depression has been an evolution, not a sudden miracle.",
        issue:"Bipolar",
        issueslug: "bipolar all",
        name:"–Patty Duke, American actress"
    },
    {   id: 3,
        quote:"In every day life, we all experience ups and downs. And sometimes this down time continues without our knowing. We all have this moment and it is perfectly fine to feel in such a way. If we all can accept this, then, no one will need to suffer because they feel alone to experience this down moment.",
        issue:"General mental health issue",
        issueslug: "general all",
        name:"–Haruka Hikita, Body, Mind, Soul Gardener"
    },
    {   id: 4,
        quote:"Move: Jump, run, squat, dance - a short burst of movements will release dopamine. When it hits me hard, I called a friend and laughed over silly things, she didn’t even need to realize what I’m going through.",
        issue:"General mental health issue",
        issueslug: "general all",
        name:"–Jacqueline Tan, Singapore"
    },
    {   id: 5,
        quote:"Grab your mask and go outside to enjoy nature. Take some pics of the beautiful changing fall and enjoy a hot cup of tea when you get back in.",
        issue:"General mental health issue",
        issueslug: "general all",
        name:"–Nikola Spoljaric, Nature Lover, Croatia"
    },
    {   id: 6,
        quote:"Everyone has his own demons to wrestle. There are some who are given more ferocious, potentially fatal monsters to fight, of which we can only vaguely imagine what it’s like and hope we would never experience ourselves. If you have an easier monster, lesser demons; if you believe you fall into the spectrum of the “normal”, then show some support to those who were dealt the harder ones.",
        issue:"General mental health issue",
        issueslug: "general all",
        name:"–Ang Sookoon, Artist"
    },
    {   id: 7,
        quote:"思い切って原因から遠ざかることは必要なことでした。自分ではどうすることもできないとき手を差し伸べてくれた人たちへの感謝は忘れません。今でも苦しいけれど、生きていこうと思えるようになりました。It was nessesary to change the dynamics of my life to stay away from the problem. I am still alive because of people who helped me when I needed it most.",
        issue:"MDD / Depression",
        issueslug: "depression all",
    },
    {   id: 16,
        quote:"Mental health problems don’t define who we are.",
        issue:"Bipolar",
        issueslug: "bipolar all"
    },
    {   id: 14,
        quote:"It’s my experience that people are a lot more sympathetic if they can see you hurting, and for the millionth time in my life I wish for measles or smallpox or some other easily understood disease just to make it easier on me and also on them.",
        issue:"General mental health issue",
        issueslug: "general all",
        name:"–Jennifer Niven, Author"
    },
    {   id: 8,
        quote:"全ての人ではないけど、話すことで相手が自分の苦しみを理解しようとしてくれたり、辛さの差はあっても同じような思いを相手も抱えていたと気づくことは少なくありません。When I am brave enought to talk about my depression, although it is not every time, I more often find people willing to understand, or they also share their own struggle.",
        issue:"MDD / Depression",
        issueslug: "depression all",
    },
    {   id: 9,
        quote:"Anxiety and depression are impervious to accolades or achievements. Anyone can be affected, despite their level of success or their place on the food chain. So why aren’t we talking about it?",
        issue:"Anxiety and Depression",
        issueslug: "anxiety depression all",
        name:"–Kristen Bell, American actress"
    },
    {   id: 10,
        quote:"I think it’s really important to take the stigma away from mental health. My brain and my heart are really important to me. I don’t know why I wouldn’t seek help to have those things be as healthy as my teeth. I go to the dentist. So why wouldn’t I go to a shrink?",
        issue:"GAD / Anxiety",
        issueslug: "anxiety all",
        name:"–Kerry Washington, American actress"
    },
    {   id: 11,
        quote:"I have never been remotely ashamed of having been depressed. Never. What’s there to be ashamed of? I went through a really tough time and I am quite proud that I got out of that.",
        issue:"MDD / Depression",
        issueslug: "depression all",
        name:"–J.K. Rowling, Author"
    },
    {   id: 12,
        quote:"There is so much pain in the world, and most of these people keep theirs secret, rolling through agonizing lives in invisible wheelchairs, dressed in invisible bodycasts.",
        issue:"MDD / Depression",
        issueslug: "depression all",
        name:"–Andrew Solomon, Writer"
    },
    {   id: 13,
        quote:"My dark days made me stronger. Or maybe I already was strong, and they made me prove it.",
        issue:"General mental health issue",
        issueslug: "general all",
        name:"–Emery Lord, Author"
    },
    {   id: 15,
        quote:"People with BPD (borderline personality disorder) are like people with third-degree burns over 90% of their bodies. Lacking emotional skin, they feel agony at the slightest touch or movement.",
        issue:"BPD / Borderline Personality Disorder",
        issueslug: "bpd all",
        name:"–Luna Greenstein on nami.org"
    },
    {   id: 19,
        quote:"When I was first diagnosed as depression, I had no idea that was depression. I just didn't know anything about it.",
        issue:"MDD / Depression",
        issueslug: "depression all"
    }
];